;•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
;Variables
;•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

[Variables]
;German Date/Time Style
;TimeFormat="%H:%M:%S"
;DateFormat="%d.%m.%Y"

;American Date/Time Style
;TimeFormat="%#I:%M:%S %p"
TimeFormat="%#I:%M %p"
DateFormat="%a %d %b %Y"

;Drive
Drive1="C"
Drive2="D"

Default_Color=200,200,200
Default_Fontface=Consolas
Default_Fontsize=10
Default_Style=NORMAL
Default_Antialias=1

Color_SysInfo=255,255,255
Color_ArchBlue=22,147,205
Color_Header=141,141,143

; this is like an orange:
Color_Orange=221,168,4
Color_Time=221,168,4

Color_Graph=112,128,143,200
Color_Graph_BG=255,255,255,48

; this is like a blue gray
Color_Date=113,129,145

Color_Gray=128,128,128
;Color_Red=255,0,0
;Color_Green=0,255,0
Color_Red=200,200,200
Color_Green=200,200,200

Color_Yellow=244, 226, 2
Color_Dark_Yellow=244,226,2,96

Header_Fontsize=12
Header_Fontstyle=Normal
Icon_Fontsize=12

Header_Bar_Size=2

Next_Line=16r
Left_Align=0
Pad_Icon=21r
Center_Align=150
Right_Align=300

Separator_Y_Offset=11r